### ISSUE TITLE
Add to NPM?

### ISSUE THREAD

**Issue by blazedd** [angular-macgyver/MacGyver#34]
Would it be possible that you submit this module to NPM so that other build systems such as webpack, browserify, requirejs, etc would be able to use your module without bower?

**Comment by adrianlee44** [comment]
Yea for sure. I can do that.

**Comment by adrianlee44** [comment]
Just published to NPM. You can find the package here, https://www.npmjs.com/package/MacGyver

**Comment by adrianlee44** [comment]
Due to a bug with NPM, packages with the same name but different cases are allowed to be registered. However, there are weird issues when trying to download/search for the package.

I'm renaming this package to angular-macgyver on npm to match the name on bower.

MacGyver will now be under https://www.npmjs.com/package/angular-macgyver.
